
name: Build and push docker image.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn clean install --file src/sample-api/pom.xml
    - name: Get sample-api version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: src/sample-api/
        push: true
        tags: kartikmavani/sample-api-${{ steps.project.outputs.version }}
        label: kartikmavani/sample-api-${{ steps.project.outputs.version }}
    - name: Image digest
      run: echo Image pushed to docker hub ${{ steps.docker_build.outputs.digest }}
